### PR TITLE
Fix for all day exclude events not taken into account

### PR DESCRIPTION
**Pull request by Gregor-Agnes**
https://github.com/lochmueller/calendarize/issues/305

### CODE REVIEW

**Comment by lochmueller** [comment]
Great. Thanks for the fix....

**Comment by lochmueller** [comment]
Note: Perhaps it is better to set the time to 0:0:0 and add https://github.com/lochmueller/calendarize/blob/master/Classes/Service/TimeTable/AbstractTimeTable.php#L23 to the time to by in sync with the other logic. !??!

**Comment by Gregor-Agnes** [comment]
Yes, didn't notice that constant. This should be changed.

**Comment by Gregor-Agnes** [comment]
I had a further thought: Are the date calculation made in UTC? If not, there is a problem.
The length of a day is not always 1 + 86399. On the day with change to daylight-saving-time, the length is 3600 seconds shorter or longer and thus the calculated time is different depending on what you add to the tiime: 1 day is not equal to 86400 seonds on that dates.

**Comment by lochmueller** [comment]
You are right... but i Have no good solution and this is quite complex :-/

**Comment by Gregor-Agnes** [comment]
If we stay with +1 day, there is no problem because the day light saving change dates are taken into account.

**Comment by lochmueller** [comment]
So, there are several place where I should change this. Perhaps we should create a new issue...

**Comment by Gregor-Agnes** [comment]
#310

**Pull request merged**
