### PR TITLE
[TASK] Add localization labels in BE module

### PR DESCRIPTION
**Pull request by sypets**
Resolves: #692

### CODE REVIEW

**Comment by lochmueller** [comment]
Hey @sypets ... thanks for the pull request. Merge....

**Comment by lochmueller** [comment]
Ähh... sorry... not mergable, because of conflicts. Will check this next week....

**Comment by sypets** [comment]
Fixed merge conflicts.

**Comment by lochmueller** [comment]
Great. Thank you... merged.

**Pull request merged**
