### PR TITLE
[Draft] New ical reader

### PR DESCRIPTION
**Pull request by okmiim**
## DateTimeUtility
The first commit replaces the DateTime argument with the DateTimeInterface in the DateTimeUtility.
It also always creates a new DateTime, to avoid unwanted siteeffect.

## ICal Reader
cal-classdiagramm

The idea is to abstract the the parsing and the results into interfaces to make it independent from the used implementation.
This is based on the pattern "Factory Method".
The DI is decided in `Services.php`.

This probaly also resolves some other issues.

This draft is already functional, but need more cleanup e.g. the import command (upgrage to PSR-14), testing,  ...

I would like to get some feedback at this stage.

- What do you think of ths structure / approach?
- Which namespace do these classes fit?
  - currently in `Services`, `Model`
- Do you an other way for the DI in `Services.php`, so that other extensions could inject their own implementation?
- (may add some more questions)

### CODE REVIEW

**Comment by lochmueller** [comment]
Hey @okmiim 
nice work. I suggest to put the whole ICS Handling in "Classes/Ics/". Then it is easier to seprate the "real Model" from the ICS Models and perhaps extract the function to a own extension in the future.
Regards,
Tim

**Comment by okmiim** [comment]
Hi @lochmueller,
I am currently testing parts of my implementation and I have a question regarding the end date of an event / configuration for all-day events.


In the specification [RFC 5545 3.6.1](https://tools.ietf.org/html/rfc5545#section-3.6.1) the end-date is non-inclusive.
```
The "DTEND" property for a "VEVENT" calendar component specifies the non-inclusive end of the event.  
```

How is the end date in the database handled (in- or exclusive)?
What values should be stored in the database?
Please **specify** for the following examples.

---
This example represents an allday event (24.10.2020).
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20201024
DTEND;VALUE=DATE:20201025
DTSTAMP:20201024T154452Z
UID:blablabla@example.com
END:VEVENT
```
**Database:**:
```
start_date 2020-10-24
end_date 2020-10-24 / 25 <------------------------------------ ???
start_time 0 (default value for all day)
end_time 0 (default value for all day)
all_day 1
open_end_time 1
```
---
An other example (shown in google calendar on these days 19.10 - 23.10):
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20201019
DTEND;VALUE=DATE:20201024
DTSTAMP:20201024T154452Z
UID:test@example.com
END:VEVENT
```
Database: see above / provide modified

---

The existing implementation handles both implementations differently.
If the end date is the day after the start exclusive, else inclusive.
https://github.com/lochmueller/calendarize/blob/34fd004f72754714c8f061c25b11c66c046d62ce/Classes/Service/IcsReaderService.php#L117-L139

**Comment by lochmueller** [comment]
Uff... good question. Best database representation for an all-day event is just the checkbox (without the enddate). If the event is only "one allday" I suggest to keep the enddate empty. Because caledarize also handle "allday events over two days".
Regards,
Tim

**Comment by okmiim** [comment]
This new implementation got a bit bigger than expected.
This stage is merge-ready (except there are improvements / complaints).
The **bold** changes are the important changes for a release note.

The importCommand migration to PSR-14 should not break other extensions, since a legacy hook dispatcher is implemented. 

## Changes

- `DateTimeUtility`
    - Replace `DateTime` with `DateTimeInterface`
        - make compatible with `ImmutableDateTime`
        - remove unintended site effects  
- Rename `Exception` to more specific `InvalidConfigurationException`
    - inherit from `RuntimeException` (recommended by typo3 docs)

- New ical parser
    - **New ical reader implementation parses the events more precisely (e.g. handles missing DTEND)**
    - Implementation
        - Main: `Sabre\VObject`
        - Fallback (e.g. from TER): `JMBTechnologyLimited\ICalDissect`
        - Decision happens inside `Configuration/Services.php`
    - `ICalEvent` - Interface to get all relevant event fields
        - `VObjectEventAdapter` and `DissectEventAdapter`  are adapters for the specific implementations
        - *Unit tests!*
    - `ICalServiceInterface` - Service to get `ICalEvent` array
        -  `VObjectICalService` and `DissectICalService`

- **Replace `importCommand` Slot with PSR-14 Event with compatibility layer**
    - Legacy hook: Still dispatches the old hook for compatibility (**prevents** breaking change)
    - Improved implementation
    - Fixes bug with updating an existing event (old configuration did not get removed)

- Import command
    - Use new ical parser (and removed `ics-parser`)
    - Improve implementation
    - **Add `--since` argument to the import command to process only newer events.**

- External time table
    - Use new ical parser

## Fixes
- New ical parser fixes #382


## Could be improved

- The import event listener can update events on a different pid than supplied by the command and won't create them on the given pid
---
https://github.com/lochmueller/calendarize/blob/4b7c2088c6243272e0a5b789964b98f0ce67627a/Classes/EventListener/ImportSingleIcalEventListener.php#L43-L46
- Ignoring the listener should happen somewhere else
- inside `Services.php` - ****Problem****: Only register the change on e.g. extension reloading
    ```php
    if (!(bool) \HDNET\Calendarize\Utility\ConfigurationUtility::get('disableDefaultEvent')) {
        $container->registerForAutoconfiguration(ImportSingleIcalEventListener::class)
            ->addTag('event.listener', [
                'identifier' => 'importSingelIcal',
                'event' => 'HDNET\Calendarize\Event\ImportSingleIcalEvent',
            ]);
    }
    ```
---
https://github.com/lochmueller/calendarize/blob/4b7c2088c6243272e0a5b789964b98f0ce67627a/Classes/EventListener/ImportSingleIcalEventListener.php#L104-L111
- Find better way to update the configuration to prevent recreation



## Future enhancements / TODOs (not this PR)

- Check / Improve time zone awareness  in parsers
- Handle temporary ical file in a service
- Use [typo3 cache](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/CachingFramework/Developer/Index.html) in `ExternalTimeTable`
- Implement recurring events
- Remove `JMBTechnologyLimited\ICalDissect` (non composer installations need to be handled!)

**Comment by lochmueller** [comment]
Hey @okmiim 
thanks for the great work and detailed description. I checked the changes (many!!!) and will merged this. Next time -> Feel free to create multiple PRs so the changes are more easy to check 👍 
You Future enhancements sound great. I will check this in the next days....
Regards,
Tim

**Pull request merged**
