### PR TITLE
Fix console commands

### LINKED ISSUE #430: ICS import does not create individual events
Hi all,

I am currently struggeling in setting up the extension in my Typo3 10 installation. I have downloaded and installed the latest version in the repo.

What I am trying to do is to set up an import from an ICS file. I already saw that several others already managed this. Till now, I tried to set up the import by using groups, events and groups in events. However, even after reindexing, there were no event created (with description, location etc.) from the ICS file. Only events with the name of the event or the configuration group are created.

Can anyone give any advices? (or any hint were to find some tutorial on this)

Thank you & br
André

### PR DESCRIPTION
**Pull request by okmiim**
Fixes #430 

## Proposed Changes
- Renames functions in command classes to Symfony Console Commands (`configure` and `execute`)
- Changed console output of the commands
- Replaces `Command.php` (will be deprecated in Typo3 v11) with `Services.yaml` with dependency injection
  - see [Feature: #89139 - Add dependency injection support for console commands](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Feature-89139-AddDependencyInjectionSupportForConsoleCommands.html)

## TODO / Questions (see et al. #440)
The import-command currently uses the signal and slot functionality, which is deprecated and will be removed in TYPO3 v12.0.
This could be replaced with the PSR-14 based events and EventDispatcherInterface.

https://github.com/lochmueller/calendarize/blob/50eaba63319a4760aedba95d2356cd4121039b0a/Classes/Command/ImportCommandController.php#L55-L66
https://github.com/lochmueller/calendarize/blob/50eaba63319a4760aedba95d2356cd4121039b0a/Classes/Slots/EventImport.php#L52

**Does a event system even make sense here? (or put all logic in ImportCommandController)**

---

The current implement in `ImportCommandController.php`/`EventImport.php` is independent from other implementations in e.g.
[IcsReaderService](https://github.com/lochmueller/calendarize/blob/50eaba63319a4760aedba95d2356cd4121039b0a/Classes/Service/IcsReaderService.php).

**Would a combination / reuse make sense and when yes what structure would you suggest?**

## Test environment
- Typo3 10.4.9
- PHP 7.2.32

### CODE REVIEW

**Comment by lochmueller** [comment]
Hey @okmiim 

great work. Thank you... Feedback for your questions:

**Slots:** There are many Signal/Slots in the extensions and all have to be replaced. I suggest to do it separatly and not in the "command commit". I created a issue for that to keep it in mind: https://github.com/lochmueller/calendarize/issues/440

**Does a event system even make sense here? (or put all logic in ImportCommandController)** I have to check. The problem is, that the command sould import Events, but also custom Object structures. In this case the Slot is needed, because EXT:caledarize don't know which fields exists in the custom event structure.

**Would a combination / reuse make sense and when yes what structure would you suggest?** Yes, your are right. In the best case there is one componenten/class that should handle ICS reading. Notice: The IcsReaderService use Sabre - but only in composer mode. So in best case there is a the fallback of the Import command part of the IcsReaderService. Should I also create a issue for that?

Regards,
Tim

**Comment by okmiim** [comment]
Thank you for your fast answer. 
You are right, this deserves a seperate issue and should not be part of a pull request.

**Comment by okmiim** [comment]
_Note_: The current implementation ot the import is a bit spammy.
It outputs for each imported event:
```
 Handle via Default Event Import Slot
 Update Event Meta data: Some important event
```

**Comment by lochmueller** [comment]
*Note: The current implementation ot the import is a bit spammy.* -> OK. Perhaps we could work with the "verbosity" option of symfony commands... I merged your current state. Thank you!

**Pull request merged**
